### URL 및 User 데이터는 environment 파일로 관리

### Trigger 테스트 - subscribe
POST {{host}}/trigger
accept: application/json
content-type: application/json

{
  "hookUrl": "NoncolumnTestUser@naaaaa.com",
  "username": "mingname",
  "hookType": "mingTest",
  "dataType": "contact",
  "eventType": "keyword",
  "distributionListUid": 123,
  "version": ""
}

> {%
client.global.set("hookId", response.body.id);
%}

### Delete Trigger 테스트 - unsubscribe
DELETE {{host}}/trigger
accept: application/json
content-type: application/json

{
  "id": {{hookId}}
}

### member-info 테스트
GET {{host}}/trigger/member-info?userName={{userName}}&userPass={{userPass}}
accept: application/json

### performList 테스트
GET {{host}}/trigger/perform-list
accept: application/json
